# file: docker-compose.yml

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fincontrol-app
    ports:
      - "7779:7779"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CRON_SECRET=${CRON_SECRET} 
    networks:
      - fincontrol-network

  db:
    image: postgres:15
    container_name: fincontrol-db
    ports:
      - "7778:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fincontrol_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fincontrol-network

  cron:
    build:
      context: ./cron
    container_name: fincontrol-cron
    depends_on:
      - app
    environment:
      # Passa o segredo para dentro do contêiner do cron
      - CRON_SECRET=${CRON_SECRET}
    networks:
      - fincontrol-network

volumes:
  postgres_data:

networks:
  fincontrol-network:
    driver: bridge